name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: '[GITHUB] Checkout repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: '[NODE.JS] Setup node.js'
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          cache-dependency-path: package-lock.json
          node-version-file: '.nvmrc'

      - name: '[NODE.JS] Installing dependencies'
        run: npm ci
        shell: bash

      - name: '[CODE STEP] Prettier check'
        run: npm run format:check
        shell: bash

      - name: '[CODE STEP] Lint check'
        run: npm run lint:check
        shell: bash

      - name: '[CODE STEP] Typecheck'
        run: npm run typecheck
        shell: bash

      - name: '[SECURITY STEP] Dependencies audit'
        run: npm audit
        shell: bash

      - name: '[BUILD STEP] Build apps'
        run: npm run build
        shell: bash

      - name: '[TEST STEP] Unit tests'
        run: npm run test:unit
        shell: bash

      - name: '[TEST STEP] Int tests'
        run: npm run test:int
        shell: bash
